import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import './globals.css';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  title: 'Arasu Chicken Center & Restaurant',
  description: 'Premium quality food and delivery.',
};
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>{children}</body>
    <html lang="en">
      <body>
        <nav style={{ padding: '20px', background: 'var(--dark)', color: 'white', display: 'flex', gap: '20px' }}>
          <a href="/" style={{ color: 'white', textDecoration: 'none', fontWeight: 'bold' }}>Home</a>
          <a href="/admin" style={{ color: 'white', textDecoration: 'none' }}>Admin Panel</a>
        </nav>
        <main style={{ padding: '40px' }}>
          {children}
        </main>
      </body>
    </html>
  );
}
